# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
development:
  <<: *default
  # database: ip_geolocation_development
  database: <%= ENV["DB_NAME"] %>



test:
  <<: *default
  database: ip_geolocation_test

# production:
#   <<: *default
#   database: ip_geolocation_api_production
#   username: ip_geolocation_api
#   password: <%= ENV["IP_GEOLOCATION_API_DATABASE_PASSWORD"] %>
